### ISSUE TITLE
Change the way to find the latest version

### ISSUE THREAD

**Issue by williamdes** [linuxserver/docker-phpmyadmin#10]
https://github.com/linuxserver/docker-phpmyadmin/blob/a42a6ec74eb4e5f0961f86e505ab6c6ff9e6fb99/Dockerfile#L49-L53

See: https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df#file-upgradephpmyadmin-sh-L61-L64

https://www.phpmyadmin.net/home_page/version.txt
See: https://stackoverflow.com/a/59825964/5155484

**Comment by thespad** [comment]
Does the version.txt always track the latest branch? We had issues with point releases for ex 5.1.x appearing ahead of 5.2.x on some of the release feeds we looked at.

**Comment by williamdes** [comment]
> Does the version.txt always track the latest branch? We had issues with point releases for ex 5.1.x appearing ahead of 5.2.x on some of the release feeds we looked at.

We always track the latest version, 5.2 was probably not announced before 5.2.0
You can use this URL without any issues. If any open directly an issue on phpmyadmin/website and we will directly look into it. Until then I can not recall about someone complaining about this file not tracking the right version
