### ISSUE TITLE
Implement sha256 integrity checking and GPG file checking

### ISSUE THREAD

**Issue by williamdes** [linuxserver/docker-phpmyadmin#11]
https://github.com/linuxserver/docker-phpmyadmin/blob/a42a6ec74eb4e5f0961f86e505ab6c6ff9e6fb99/Dockerfile#L56

See: https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df#file-upgradephpmyadmin-sh-L96-L107
See: https://github.com/phpmyadmin/docker/blob/5.2.0/Dockerfile-alpine.template#L89-L103

**Comment by thespad** [comment]
Thanks, I'll take a look at this when I get a chance.
