### ISSUE TITLE
[BUG] PMA_CONFIG_BASE64 and PMA_USER_CONFIG_BASE64 do not work

### ISSUE THREAD

**Issue by xboxfly15** [linuxserver/docker-phpmyadmin#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using lscr.io/linuxserver/phpmyadmin:latest PMA_USER_CONFIG_BASE64 and PMA_CONFIG_BASE64 do not work at all.
All other environment variables work except for them two.

### Expected Behavior

Work the same as the official image which overrides any previous environment variables.

### Steps To Reproduce

1. Use  lscr.io/linuxserver/phpmyadmin:latest
2. Use https://pr.gg/base64/ to generate base64
3. Enter something to easily tell if env variable is working, like
```
<?php
$cfg['Servers'] = [
1 => [
'auth_type' => 'cookie',
'host' => 'mysqldb',
'verbose' => 'PMA_USER_CONFIG_BASE64 works',
'port' => 3306,
],
2 => [
'auth_type' => 'cookie',
'host' => 'mysqldb',
'verbose' => 'PMA_USER_CONFIG_BASE64 works',
'port' => 3306,
],
];
```
5. Set PMA_USER_CONFIG_BASE64 to the result
6. Visit PHPMyAdmin and see if server selector shows "PMA_USER_CONFIG_BASE64 works"

### CPU architecture

x86-64

### Docker creation

```bash
n/a
```

### Container logs

```bash
n/a. PHPMyAdmin works fine except for these 2 env variables.
```

**Comment by thespad** [comment]
Please provide the actual run/compose you're trying to use with this env.

**Comment by xboxfly15** [comment]
I’m using Coolify so there is none. It’s just the image with that environment variable.On 26 Nov 2024, at 3:38 pm, Adam ***@***.***> wrote:﻿
Please provide the actual run/compose you're trying to use with this env.

**Comment by thespad** [comment]
`PMA_CONFIG_BASE64` & `PMA_USER_CONFIG_BASE64` are not built-in envs that phpmyadmin can read, the official docker image does its own processing of them to replace the config files. I'll need to open a PR to make similar affordances for our image.

**Comment by xboxfly15** [comment]
Cheers. Yeah I could not see any code in this repo that added such which I thought was weird as I was just lead to believe it supported all env variables based on the README ``We support all of the official [environment variables](https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables) for configuration...`` which is why I opened this issue.
