### ISSUE TITLE
What does this image add to the existing official Docker hub phpMyAdmin image ?

### ISSUE THREAD

**Issue by williamdes** [linuxserver/docker-phpmyadmin#9]
Hi from the @phpmyadmin team !
I am just curious: What does this image add to the existing official Docker hub phpMyAdmin image ?

**Comment by thespad** [comment]
It doesn't add anything per se (over our usual pipeline benefits) but the official versions only offer a serverless FPM image or one with Apache bundled and both are over 500Mb - ours bundles nginx and is ~130Mb.

**Comment by williamdes** [comment]
> It doesn't add anything per se (over our usual pipeline benefits) but the official versions only offer a serverless FPM image or one with Apache bundled and both are over 500Mb - ours bundles nginx and is ~130Mb.

Indeed this is a missing variant that we can not provide, because it would involve a process supervisor (for fpm and nginx process to be insured alive) and that is not acceptable for docker official images

See: https://github.com/phpmyadmin/docker/issues/346

**Comment by thespad** [comment]
All our images use s6 as a supervisor and our go-to is Alpine/nginx for serving web content so it made it an obvious choice. When I'm back from hoiliday I'll look at implementing all your suggestions and call out in the readme what our "USP" is compared to the official image.

**Comment by williamdes** [comment]
> All our images use s6 as a supervisor and our go-to is Alpine/nginx for serving web content so it made it an obvious choice. When I'm back from hoiliday I'll look at implementing all your suggestions and call out in the readme what our "USP" is compared to the official image.

Thanks
I would also love to provide this on the official image...
Nginx is so cool and performant !
